Stop the service when upgrading only on postinst
It reduces the downtime significantly.

diff --git a/templates/postinst b/templates/postinst
--- a/templates/postinst
+++ b/templates/postinst
@@ -76,6 +76,31 @@ start_service () {
   fi
 }
 
+stop_service () {
+  : "${1:?'Service name was not defined'}"
+  declare -r service_name="$1"
+
+  if [[ "$init_type" == 'auto' || "$init_type" == 'systemd' || "$init_type" == 'upstart' || "$init_type" == 'sysv' ]]; then
+    if hash systemctl 2> /dev/null; then
+      systemctl disable "$service_name.service" && \
+      systemctl stop "$service_name.service" || \
+      echo "$service_name wasn't even running!"
+    elif hash service 2> /dev/null; then
+      service "$service_name" stop || echo "$service_name wasn't even running!"
+    elif hash stop 2> /dev/null; then
+      stop "$service_name" || echo "$service_name wasn't even running!"
+    elif hash update-rc.d 2> /dev/null; then
+      {
+        update-rc.d "$service_name" remove && \
+        "/etc/init.d/$service_name" stop
+      } || "$service_name wasn't even running!"
+    else
+      echo "Your system does not appear to use upstart, systemd or sysv, so $service_name could not be stopped"
+      echo 'Unless these systems were removed since install, no processes have been left running'
+    fi
+  fi
+}
+
 dependency_install() {
   : "${1:?'Package name was not defined'}"
   cd "{{ node_deb_install_dir }}/$1/app"
@@ -123,5 +148,6 @@ if [[ "$init_type" != 'none' ]]; then
   mkdir -p '/var/log/{{ node_deb_package_name }}'
   chown -R '{{ node_deb_user }}:{{ node_deb_group }}' '/var/log/{{ node_deb_package_name }}'
 
+  stop_service '{{ node_deb_package_name }}'
   start_service '{{ node_deb_package_name }}'
 fi
